In [169]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Credit Risk Assessment

In [170]:
import pandas as pd
import numpy as np

import src.utils as utils

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Business Understanding

blabla

## Objective Metrics

blabla

## Data Preparation

In [171]:
df = pd.read_csv('input/loan_data_2007_2014.csv', low_memory=False)

utils.skim_data(df)

Total duplicate rows: 0
DF shape: (466285, 75)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,Unnamed: 0,int64,0.000,0.0,0.0,466285,100.00,"[0, 1, 2, 3, 4]"
1,id,int64,0.000,0.0,0.0,466285,100.00,"[1077501, 1077430, 1077175, 1076863, 1075358]"
2,member_id,int64,0.000,0.0,0.0,466285,100.00,"[1296599, 1314167, 1313524, 1277178, 1311748]"
3,loan_amnt,int64,0.000,0.0,0.0,1352,0.29,"[5000, 2500, 2400, 10000, 3000]"
4,funded_amnt,int64,0.000,0.0,0.0,1354,0.29,"[5000, 2500, 2400, 10000, 3000]"
5,funded_amnt_inv,float64,0.000,0.0,0.05,9854,2.11,"[4975.0, 2500.0, 2400.0, 10000.0, 3000.0]"
6,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
7,int_rate,float64,0.000,0.0,0.0,506,0.11,"[10.65, 15.27, 15.96, 13.49, 12.69]"
8,installment,float64,0.000,0.0,0.0,55622,11.93,"[162.87, 59.83, 84.33, 339.31, 67.79]"
9,grade,object,0.000,-,-,7,0.00,"[B, C, A, E, F]"
10,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, B5]"
11,emp_title,object,5.917,-,-,205475,44.07,"[Ryder, AIR RESOURCES BOARD, University Medica..."
12,emp_length,object,4.505,-,-,11,0.00,"[10+ years, < 1 year, 1 year, 3 years, 8 years]"
13,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
14,annual_inc,float64,0.001,0.0,0.0,31901,6.84,"[24000.0, 30000.0, 12252.0, 49200.0, 80000.0]"
15,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
16,issue_d,object,0.000,-,-,91,0.02,"[Dec-11, Nov-11, Oct-11, Sep-11, Aug-11]"
17,loan_status,object,0.000,-,-,9,0.00,"[Fully Paid, Charged Off, Current, Default, La..."
18,pymnt_plan,object,0.000,-,-,2,0.00,"[n, y]"
19,url,object,0.000,-,-,466285,100.00,[https://www.lendingclub.com/browse/loanDetail...
20,desc,object,72.982,-,-,124435,26.69,[ Borrower added on 12/22/11 > I need to upgr...
21,purpose,object,0.000,-,-,14,0.00,"[credit_card, car, small_business, other, wedd..."
22,title,object,0.005,-,-,63098,13.53,"[Computer, bike, real estate business, persone..."
23,zip_code,object,0.000,-,-,888,0.19,"[860xx, 309xx, 606xx, 917xx, 972xx]"
24,addr_state,object,0.000,-,-,50,0.01,"[AZ, GA, IL, CA, OR]"
25,dti,float64,0.000,0.0,0.078,3997,0.86,"[27.65, 1.0, 8.72, 20.0, 17.94]"
26,delinq_2yrs,float64,0.006,0.0,82.129,24,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
27,earliest_cr_line,object,0.006,-,-,664,0.14,"[Jan-85, Apr-99, Nov-01, Feb-96, Jan-96]"
28,inq_last_6mths,float64,0.006,0.0,51.792,28,0.01,"[1.0, 5.0, 2.0, 0.0, 3.0]"
29,mths_since_last_delinq,float64,53.691,0.0,0.262,145,0.03,"[35.0, 38.0, 61.0, 8.0, 20.0]"
30,mths_since_last_record,float64,86.567,0.0,0.274,123,0.03,"[113.0, 105.0, 97.0, 33.0, 93.0]"
31,open_acc,float64,0.006,0.0,0.002,62,0.01,"[3.0, 2.0, 10.0, 15.0, 9.0]"
32,pub_rec,float64,0.006,0.0,86.834,26,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
33,revol_bal,int64,0.000,0.0,0.487,58142,12.47,"[13648, 1687, 2956, 5598, 27783]"
34,revol_util,float64,0.073,0.0,0.49,1269,0.27,"[83.7, 9.4, 98.5, 21.0, 53.9]"
35,total_acc,float64,0.006,0.0,0.0,112,0.02,"[9.0, 4.0, 10.0, 37.0, 38.0]"
36,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
37,out_prncp,float64,0.000,0.0,49.326,135665,29.09,"[0.0, 766.9, 1889.15, 2695.31, 3193.13]"
38,out_prncp_inv,float64,0.000,0.0,49.326,141189,30.28,"[0.0, 766.9, 1889.15, 2688.53, 3186.72]"
39,total_pymnt,float64,0.000,0.0,0.019,351609,75.41,"[5861.071414, 1008.71, 3003.653644, 12226.3022..."
40,total_pymnt_inv,float64,0.000,0.0,0.078,347659,74.56,"[5831.78, 1008.71, 3003.65, 12226.3, 3242.17]"
41,total_rec_prncp,float64,0.000,0.0,0.086,172713,37.04,"[5000.0, 456.46, 2400.0, 10000.0, 2233.1]"
42,total_rec_int,float64,0.000,0.0,0.081,270249,57.96,"[861.07, 435.17, 603.65, 2209.33, 1009.07]"
43,total_rec_late_fee,float64,0.000,0.0,97.71,5808,1.25,"[0.0, 16.97, 15.0, 24.17, 14.98883533]"
44,recoveries,float64,0.000,0.0,94.773,22773,4.88,"[0.0, 117.08, 189.06, 269.29, 444.3]"
45,collection_recovery_fee,float64,0.000,0.0,95.023,20275,4.35,"[0.0, 1.11, 2.09, 2.52, 4.16]"
46,last_pymnt_d,object,0.081,-,-,98,0.02,"[Jan-15, Apr-13, Jun-14, Jan-16, Apr-12]"
47,last_pymnt_amnt,float64,0.000,0.0,0.084,198194,42.50,"[171.62, 119.66, 649.91, 357.48, 67.79]"
48,next_pymnt_d,object,48.729,-,-,100,0.02,"[Feb-16, Jan-16, Sep-13, Feb-14, May-14]"
49,last_credit_pull_d,object,0.009,-,-,103,0.02,"[Jan-16, Sep-13, Jan-15, Sep-15, Dec-14]"
50,collections_12_mths_ex_med,float64,0.031,0.0,99.13,9,0.00,"[0.0, 1.0, 2.0, 4.0, 3.0]"
51,mths_since_last_major_derog,float64,78.774,0.0,0.017,162,0.03,"[53.0, 34.0, 54.0, 69.0, 7.0]"
52,policy_code,int64,0.000,0.0,0.0,1,0.00,[1]
53,application_type,object,0.000,-,-,1,0.00,[INDIVIDUAL]
54,annual_inc_joint,float64,100.000,0.0,0.0,0,0.00,[]
55,dti_joint,float64,100.000,0.0,0.0,0,0.00,[]
56,verification_status_joint,float64,100.000,0.0,0.0,0,0.00,[]
57,acc_now_delinq,float64,0.006,0.0,99.622,6,0.00,"[0.0, 1.0, 2.0, 3.0, 5.0]"
58,tot_coll_amt,float64,15.071,0.0,74.259,6321,1.36,"[0.0, 15386.0, 1514.0, 154.0, 539.0]"
59,tot_cur_bal,float64,15.071,0.0,0.017,220690,47.33,"[114834.0, 14123.0, 267646.0, 13605.0, 272492.0]"
60,open_acc_6m,float64,100.000,0.0,0.0,0,0.00,[]
61,open_il_6m,float64,100.000,0.0,0.0,0,0.00,[]
62,open_il_12m,float64,100.000,0.0,0.0,0,0.00,[]
63,open_il_24m,float64,100.000,0.0,0.0,0,0.00,[]
64,mths_since_rcnt_il,float64,100.000,0.0,0.0,0,0.00,[]
65,total_bal_il,float64,100.000,0.0,0.0,0,0.00,[]
66,il_util,float64,100.000,0.0,0.0,0,0.00,[]
67,open_rv_12m,float64,100.000,0.0,0.0,0,0.00,[]
68,open_rv_24m,float64,100.000,0.0,0.0,0,0.00,[]
69,max_bal_bc,float64,100.000,0.0,0.0,0,0.00,[]
70,all_util,float64,100.000,0.0,0.0,0,0.00,[]
71,total_rev_hi_lim,float64,15.071,0.0,0.033,14612,3.13,"[59900.0, 15100.0, 61100.0, 8100.0, 15400.0]"
72,inq_fi,float64,100.000,0.0,0.0,0,0.00,[]
73,total_cu_tl,float64,100.000,0.0,0.0,0,0.00,[]
74,inq_last_12m,float64,100.000,0.0,0.0,0,0.00,[]

Berdasarkan hasil `skim_data`, terdapat 466.285 baris data dan 75 kolom fitur. Kolom targetnya adalah `loan_status`. Dari jumlah baris sebanyak itu, tidak terlihat ada data duplikat. Meskipun demikian, 75 fitur ini masih dapat dikurangi untuk mempermudah eksplorasi dan membuat model jadi lebih efisien dan akurat. Ada lima langkah yang bisa saya lakukan untuk mengurangi jumlah fitur ini, yaitu:

- Filter berdasarkan identitas dan informasi administratif: membuang fitur seperti nama dan ID nasabah, karena fitur seperti itu tidak memiliki nilai prediktif.
- Filter berdasarkan kualitas data: membuang (a) fitur yang memiliki *missing values* yang terlalu banyak dan (b) fitur yang hanya memiliki satu nilai unik karena fitur ini tidak memberikan informasi pembeda bagi model.
- Filter berdasarkan fitur yang berpotensi menimbulkan *data leakage*.
- Filter berdasarkan fitur yang memiliki variasi rendah.
- Filter berdasarkan fitur yang memiliki jumlah nilai 0 yang tinggi.

Selain mengurangi jumlah fitur, saya juga perlu mengubah fitur-fitur kategorikal yang bisa diubah menjadi fitur numerik.

### Identifying IDs and Adminstrative Informations

Fitur-fitur yang tergolong dalam kategori ini adalah `id`, `member_id`, `url`, `desc`, `policy_code`, `Unnamed: 0`, `emp_title`, `title`, dan `zip_code`.

In [172]:
df = df.drop(columns=['id', 'member_id', 'url', 'desc', 'policy_code', 'Unnamed: 0', 'emp_title', 'title', 'zip_code'])
skim_result = utils.skim_data(df)

skim_result

Total duplicate rows: 0
DF shape: (466285, 66)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,loan_amnt,int64,0.000,0.0,0.0,1352,0.29,"[5000, 2500, 2400, 10000, 3000]"
1,funded_amnt,int64,0.000,0.0,0.0,1354,0.29,"[5000, 2500, 2400, 10000, 3000]"
2,funded_amnt_inv,float64,0.000,0.0,0.05,9854,2.11,"[4975.0, 2500.0, 2400.0, 10000.0, 3000.0]"
3,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
4,int_rate,float64,0.000,0.0,0.0,506,0.11,"[10.65, 15.27, 15.96, 13.49, 12.69]"
5,installment,float64,0.000,0.0,0.0,55622,11.93,"[162.87, 59.83, 84.33, 339.31, 67.79]"
6,grade,object,0.000,-,-,7,0.00,"[B, C, A, E, F]"
7,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, B5]"
8,emp_length,object,4.505,-,-,11,0.00,"[10+ years, < 1 year, 1 year, 3 years, 8 years]"
9,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
10,annual_inc,float64,0.001,0.0,0.0,31901,6.84,"[24000.0, 30000.0, 12252.0, 49200.0, 80000.0]"
11,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
12,issue_d,object,0.000,-,-,91,0.02,"[Dec-11, Nov-11, Oct-11, Sep-11, Aug-11]"
13,loan_status,object,0.000,-,-,9,0.00,"[Fully Paid, Charged Off, Current, Default, La..."
14,pymnt_plan,object,0.000,-,-,2,0.00,"[n, y]"
15,purpose,object,0.000,-,-,14,0.00,"[credit_card, car, small_business, other, wedd..."
16,addr_state,object,0.000,-,-,50,0.01,"[AZ, GA, IL, CA, OR]"
17,dti,float64,0.000,0.0,0.078,3997,0.86,"[27.65, 1.0, 8.72, 20.0, 17.94]"
18,delinq_2yrs,float64,0.006,0.0,82.129,24,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
19,earliest_cr_line,object,0.006,-,-,664,0.14,"[Jan-85, Apr-99, Nov-01, Feb-96, Jan-96]"
20,inq_last_6mths,float64,0.006,0.0,51.792,28,0.01,"[1.0, 5.0, 2.0, 0.0, 3.0]"
21,mths_since_last_delinq,float64,53.691,0.0,0.262,145,0.03,"[35.0, 38.0, 61.0, 8.0, 20.0]"
22,mths_since_last_record,float64,86.567,0.0,0.274,123,0.03,"[113.0, 105.0, 97.0, 33.0, 93.0]"
23,open_acc,float64,0.006,0.0,0.002,62,0.01,"[3.0, 2.0, 10.0, 15.0, 9.0]"
24,pub_rec,float64,0.006,0.0,86.834,26,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
25,revol_bal,int64,0.000,0.0,0.487,58142,12.47,"[13648, 1687, 2956, 5598, 27783]"
26,revol_util,float64,0.073,0.0,0.49,1269,0.27,"[83.7, 9.4, 98.5, 21.0, 53.9]"
27,total_acc,float64,0.006,0.0,0.0,112,0.02,"[9.0, 4.0, 10.0, 37.0, 38.0]"
28,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
29,out_prncp,float64,0.000,0.0,49.326,135665,29.09,"[0.0, 766.9, 1889.15, 2695.31, 3193.13]"
30,out_prncp_inv,float64,0.000,0.0,49.326,141189,30.28,"[0.0, 766.9, 1889.15, 2688.53, 3186.72]"
31,total_pymnt,float64,0.000,0.0,0.019,351609,75.41,"[5861.071414, 1008.71, 3003.653644, 12226.3022..."
32,total_pymnt_inv,float64,0.000,0.0,0.078,347659,74.56,"[5831.78, 1008.71, 3003.65, 12226.3, 3242.17]"
33,total_rec_prncp,float64,0.000,0.0,0.086,172713,37.04,"[5000.0, 456.46, 2400.0, 10000.0, 2233.1]"
34,total_rec_int,float64,0.000,0.0,0.081,270249,57.96,"[861.07, 435.17, 603.65, 2209.33, 1009.07]"
35,total_rec_late_fee,float64,0.000,0.0,97.71,5808,1.25,"[0.0, 16.97, 15.0, 24.17, 14.98883533]"
36,recoveries,float64,0.000,0.0,94.773,22773,4.88,"[0.0, 117.08, 189.06, 269.29, 444.3]"
37,collection_recovery_fee,float64,0.000,0.0,95.023,20275,4.35,"[0.0, 1.11, 2.09, 2.52, 4.16]"
38,last_pymnt_d,object,0.081,-,-,98,0.02,"[Jan-15, Apr-13, Jun-14, Jan-16, Apr-12]"
39,last_pymnt_amnt,float64,0.000,0.0,0.084,198194,42.50,"[171.62, 119.66, 649.91, 357.48, 67.79]"
40,next_pymnt_d,object,48.729,-,-,100,0.02,"[Feb-16, Jan-16, Sep-13, Feb-14, May-14]"
41,last_credit_pull_d,object,0.009,-,-,103,0.02,"[Jan-16, Sep-13, Jan-15, Sep-15, Dec-14]"
42,collections_12_mths_ex_med,float64,0.031,0.0,99.13,9,0.00,"[0.0, 1.0, 2.0, 4.0, 3.0]"
43,mths_since_last_major_derog,float64,78.774,0.0,0.017,162,0.03,"[53.0, 34.0, 54.0, 69.0, 7.0]"
44,application_type,object,0.000,-,-,1,0.00,[INDIVIDUAL]
45,annual_inc_joint,float64,100.000,0.0,0.0,0,0.00,[]
46,dti_joint,float64,100.000,0.0,0.0,0,0.00,[]
47,verification_status_joint,float64,100.000,0.0,0.0,0,0.00,[]
48,acc_now_delinq,float64,0.006,0.0,99.622,6,0.00,"[0.0, 1.0, 2.0, 3.0, 5.0]"
49,tot_coll_amt,float64,15.071,0.0,74.259,6321,1.36,"[0.0, 15386.0, 1514.0, 154.0, 539.0]"
50,tot_cur_bal,float64,15.071,0.0,0.017,220690,47.33,"[114834.0, 14123.0, 267646.0, 13605.0, 272492.0]"
51,open_acc_6m,float64,100.000,0.0,0.0,0,0.00,[]
52,open_il_6m,float64,100.000,0.0,0.0,0,0.00,[]
53,open_il_12m,float64,100.000,0.0,0.0,0,0.00,[]
54,open_il_24m,float64,100.000,0.0,0.0,0,0.00,[]
55,mths_since_rcnt_il,float64,100.000,0.0,0.0,0,0.00,[]
56,total_bal_il,float64,100.000,0.0,0.0,0,0.00,[]
57,il_util,float64,100.000,0.0,0.0,0,0.00,[]
58,open_rv_12m,float64,100.000,0.0,0.0,0,0.00,[]
59,open_rv_24m,float64,100.000,0.0,0.0,0,0.00,[]
60,max_bal_bc,float64,100.000,0.0,0.0,0,0.00,[]
61,all_util,float64,100.000,0.0,0.0,0,0.00,[]
62,total_rev_hi_lim,float64,15.071,0.0,0.033,14612,3.13,"[59900.0, 15100.0, 61100.0, 8100.0, 15400.0]"
63,inq_fi,float64,100.000,0.0,0.0,0,0.00,[]
64,total_cu_tl,float64,100.000,0.0,0.0,0,0.00,[]
65,inq_last_12m,float64,100.000,0.0,0.0,0,0.00,[]

### Low-Quality Features

Ada dua hal yang harus dilakukan dalam tahap ini:

- Menghapus fitur yang memiliki *missing values* > 50%, dan
- Menghapus fitur yang hanya memiliki satu nilai.

In [173]:
null_features = skim_result[skim_result['null_%'] > 50]['feature'].tolist()
print(f'Null features: {null_features}')
df = df.drop(columns=null_features)
skim_result = utils.skim_data(df) # update the skim result

skim_result

Null features: ['mths_since_last_delinq', 'mths_since_last_record', 'mths_since_last_major_derog', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'open_acc_6m', 'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'inq_fi', 'total_cu_tl', 'inq_last_12m']
Total duplicate rows: 0
DF shape: (466285, 46)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,loan_amnt,int64,0.000,0.0,0.0,1352,0.29,"[5000, 2500, 2400, 10000, 3000]"
1,funded_amnt,int64,0.000,0.0,0.0,1354,0.29,"[5000, 2500, 2400, 10000, 3000]"
2,funded_amnt_inv,float64,0.000,0.0,0.05,9854,2.11,"[4975.0, 2500.0, 2400.0, 10000.0, 3000.0]"
3,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
4,int_rate,float64,0.000,0.0,0.0,506,0.11,"[10.65, 15.27, 15.96, 13.49, 12.69]"
5,installment,float64,0.000,0.0,0.0,55622,11.93,"[162.87, 59.83, 84.33, 339.31, 67.79]"
6,grade,object,0.000,-,-,7,0.00,"[B, C, A, E, F]"
7,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, B5]"
8,emp_length,object,4.505,-,-,11,0.00,"[10+ years, < 1 year, 1 year, 3 years, 8 years]"
9,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
10,annual_inc,float64,0.001,0.0,0.0,31901,6.84,"[24000.0, 30000.0, 12252.0, 49200.0, 80000.0]"
11,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
12,issue_d,object,0.000,-,-,91,0.02,"[Dec-11, Nov-11, Oct-11, Sep-11, Aug-11]"
13,loan_status,object,0.000,-,-,9,0.00,"[Fully Paid, Charged Off, Current, Default, La..."
14,pymnt_plan,object,0.000,-,-,2,0.00,"[n, y]"
15,purpose,object,0.000,-,-,14,0.00,"[credit_card, car, small_business, other, wedd..."
16,addr_state,object,0.000,-,-,50,0.01,"[AZ, GA, IL, CA, OR]"
17,dti,float64,0.000,0.0,0.078,3997,0.86,"[27.65, 1.0, 8.72, 20.0, 17.94]"
18,delinq_2yrs,float64,0.006,0.0,82.129,24,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
19,earliest_cr_line,object,0.006,-,-,664,0.14,"[Jan-85, Apr-99, Nov-01, Feb-96, Jan-96]"
20,inq_last_6mths,float64,0.006,0.0,51.792,28,0.01,"[1.0, 5.0, 2.0, 0.0, 3.0]"
21,open_acc,float64,0.006,0.0,0.002,62,0.01,"[3.0, 2.0, 10.0, 15.0, 9.0]"
22,pub_rec,float64,0.006,0.0,86.834,26,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
23,revol_bal,int64,0.000,0.0,0.487,58142,12.47,"[13648, 1687, 2956, 5598, 27783]"
24,revol_util,float64,0.073,0.0,0.49,1269,0.27,"[83.7, 9.4, 98.5, 21.0, 53.9]"
25,total_acc,float64,0.006,0.0,0.0,112,0.02,"[9.0, 4.0, 10.0, 37.0, 38.0]"
26,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
27,out_prncp,float64,0.000,0.0,49.326,135665,29.09,"[0.0, 766.9, 1889.15, 2695.31, 3193.13]"
28,out_prncp_inv,float64,0.000,0.0,49.326,141189,30.28,"[0.0, 766.9, 1889.15, 2688.53, 3186.72]"
29,total_pymnt,float64,0.000,0.0,0.019,351609,75.41,"[5861.071414, 1008.71, 3003.653644, 12226.3022..."
30,total_pymnt_inv,float64,0.000,0.0,0.078,347659,74.56,"[5831.78, 1008.71, 3003.65, 12226.3, 3242.17]"
31,total_rec_prncp,float64,0.000,0.0,0.086,172713,37.04,"[5000.0, 456.46, 2400.0, 10000.0, 2233.1]"
32,total_rec_int,float64,0.000,0.0,0.081,270249,57.96,"[861.07, 435.17, 603.65, 2209.33, 1009.07]"
33,total_rec_late_fee,float64,0.000,0.0,97.71,5808,1.25,"[0.0, 16.97, 15.0, 24.17, 14.98883533]"
34,recoveries,float64,0.000,0.0,94.773,22773,4.88,"[0.0, 117.08, 189.06, 269.29, 444.3]"
35,collection_recovery_fee,float64,0.000,0.0,95.023,20275,4.35,"[0.0, 1.11, 2.09, 2.52, 4.16]"
36,last_pymnt_d,object,0.081,-,-,98,0.02,"[Jan-15, Apr-13, Jun-14, Jan-16, Apr-12]"
37,last_pymnt_amnt,float64,0.000,0.0,0.084,198194,42.50,"[171.62, 119.66, 649.91, 357.48, 67.79]"
38,next_pymnt_d,object,48.729,-,-,100,0.02,"[Feb-16, Jan-16, Sep-13, Feb-14, May-14]"
39,last_credit_pull_d,object,0.009,-,-,103,0.02,"[Jan-16, Sep-13, Jan-15, Sep-15, Dec-14]"
40,collections_12_mths_ex_med,float64,0.031,0.0,99.13,9,0.00,"[0.0, 1.0, 2.0, 4.0, 3.0]"
41,application_type,object,0.000,-,-,1,0.00,[INDIVIDUAL]
42,acc_now_delinq,float64,0.006,0.0,99.622,6,0.00,"[0.0, 1.0, 2.0, 3.0, 5.0]"
43,tot_coll_amt,float64,15.071,0.0,74.259,6321,1.36,"[0.0, 15386.0, 1514.0, 154.0, 539.0]"
44,tot_cur_bal,float64,15.071,0.0,0.017,220690,47.33,"[114834.0, 14123.0, 267646.0, 13605.0, 272492.0]"
45,total_rev_hi_lim,float64,15.071,0.0,0.033,14612,3.13,"[59900.0, 15100.0, 61100.0, 8100.0, 15400.0]"

Terdapat 20 fitur yang memiliki proporsi *missing value* di atas 50%, dan semuanya telah dihapus dari data. Sekarang mari lihat fitur yang hanya memiliki satu nilai.

In [174]:
one_value_features = skim_result[skim_result['n_unique'] == 1]['feature'].tolist()
df = df.drop(columns=one_value_features)
skim_result = utils.skim_data(df)

skim_result

Total duplicate rows: 0
DF shape: (466285, 45)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,loan_amnt,int64,0.000,0.0,0.0,1352,0.29,"[5000, 2500, 2400, 10000, 3000]"
1,funded_amnt,int64,0.000,0.0,0.0,1354,0.29,"[5000, 2500, 2400, 10000, 3000]"
2,funded_amnt_inv,float64,0.000,0.0,0.05,9854,2.11,"[4975.0, 2500.0, 2400.0, 10000.0, 3000.0]"
3,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
4,int_rate,float64,0.000,0.0,0.0,506,0.11,"[10.65, 15.27, 15.96, 13.49, 12.69]"
5,installment,float64,0.000,0.0,0.0,55622,11.93,"[162.87, 59.83, 84.33, 339.31, 67.79]"
6,grade,object,0.000,-,-,7,0.00,"[B, C, A, E, F]"
7,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, B5]"
8,emp_length,object,4.505,-,-,11,0.00,"[10+ years, < 1 year, 1 year, 3 years, 8 years]"
9,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
10,annual_inc,float64,0.001,0.0,0.0,31901,6.84,"[24000.0, 30000.0, 12252.0, 49200.0, 80000.0]"
11,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
12,issue_d,object,0.000,-,-,91,0.02,"[Dec-11, Nov-11, Oct-11, Sep-11, Aug-11]"
13,loan_status,object,0.000,-,-,9,0.00,"[Fully Paid, Charged Off, Current, Default, La..."
14,pymnt_plan,object,0.000,-,-,2,0.00,"[n, y]"
15,purpose,object,0.000,-,-,14,0.00,"[credit_card, car, small_business, other, wedd..."
16,addr_state,object,0.000,-,-,50,0.01,"[AZ, GA, IL, CA, OR]"
17,dti,float64,0.000,0.0,0.078,3997,0.86,"[27.65, 1.0, 8.72, 20.0, 17.94]"
18,delinq_2yrs,float64,0.006,0.0,82.129,24,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
19,earliest_cr_line,object,0.006,-,-,664,0.14,"[Jan-85, Apr-99, Nov-01, Feb-96, Jan-96]"
20,inq_last_6mths,float64,0.006,0.0,51.792,28,0.01,"[1.0, 5.0, 2.0, 0.0, 3.0]"
21,open_acc,float64,0.006,0.0,0.002,62,0.01,"[3.0, 2.0, 10.0, 15.0, 9.0]"
22,pub_rec,float64,0.006,0.0,86.834,26,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
23,revol_bal,int64,0.000,0.0,0.487,58142,12.47,"[13648, 1687, 2956, 5598, 27783]"
24,revol_util,float64,0.073,0.0,0.49,1269,0.27,"[83.7, 9.4, 98.5, 21.0, 53.9]"
25,total_acc,float64,0.006,0.0,0.0,112,0.02,"[9.0, 4.0, 10.0, 37.0, 38.0]"
26,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
27,out_prncp,float64,0.000,0.0,49.326,135665,29.09,"[0.0, 766.9, 1889.15, 2695.31, 3193.13]"
28,out_prncp_inv,float64,0.000,0.0,49.326,141189,30.28,"[0.0, 766.9, 1889.15, 2688.53, 3186.72]"
29,total_pymnt,float64,0.000,0.0,0.019,351609,75.41,"[5861.071414, 1008.71, 3003.653644, 12226.3022..."
30,total_pymnt_inv,float64,0.000,0.0,0.078,347659,74.56,"[5831.78, 1008.71, 3003.65, 12226.3, 3242.17]"
31,total_rec_prncp,float64,0.000,0.0,0.086,172713,37.04,"[5000.0, 456.46, 2400.0, 10000.0, 2233.1]"
32,total_rec_int,float64,0.000,0.0,0.081,270249,57.96,"[861.07, 435.17, 603.65, 2209.33, 1009.07]"
33,total_rec_late_fee,float64,0.000,0.0,97.71,5808,1.25,"[0.0, 16.97, 15.0, 24.17, 14.98883533]"
34,recoveries,float64,0.000,0.0,94.773,22773,4.88,"[0.0, 117.08, 189.06, 269.29, 444.3]"
35,collection_recovery_fee,float64,0.000,0.0,95.023,20275,4.35,"[0.0, 1.11, 2.09, 2.52, 4.16]"
36,last_pymnt_d,object,0.081,-,-,98,0.02,"[Jan-15, Apr-13, Jun-14, Jan-16, Apr-12]"
37,last_pymnt_amnt,float64,0.000,0.0,0.084,198194,42.50,"[171.62, 119.66, 649.91, 357.48, 67.79]"
38,next_pymnt_d,object,48.729,-,-,100,0.02,"[Feb-16, Jan-16, Sep-13, Feb-14, May-14]"
39,last_credit_pull_d,object,0.009,-,-,103,0.02,"[Jan-16, Sep-13, Jan-15, Sep-15, Dec-14]"
40,collections_12_mths_ex_med,float64,0.031,0.0,99.13,9,0.00,"[0.0, 1.0, 2.0, 4.0, 3.0]"
41,acc_now_delinq,float64,0.006,0.0,99.622,6,0.00,"[0.0, 1.0, 2.0, 3.0, 5.0]"
42,tot_coll_amt,float64,15.071,0.0,74.259,6321,1.36,"[0.0, 15386.0, 1514.0, 154.0, 539.0]"
43,tot_cur_bal,float64,15.071,0.0,0.017,220690,47.33,"[114834.0, 14123.0, 267646.0, 13605.0, 272492.0]"
44,total_rev_hi_lim,float64,15.071,0.0,0.033,14612,3.13,"[59900.0, 15100.0, 61100.0, 8100.0, 15400.0]"

Hanya terdapat satu fitur yang memiliki satu nilai, yaitu `application_type`. Fitur tersebut telah dihapus.

### Transforming non-numerical data

In [175]:
categorical_cols = skim_result[skim_result['dtype'] == 'object']['feature'].tolist()
df[categorical_cols].sample(10)

,term,grade,sub_grade,emp_length,home_ownership,verification_status,issue_d,loan_status,pymnt_plan,purpose,addr_state,earliest_cr_line,initial_list_status,last_pymnt_d,next_pymnt_d,last_credit_pull_d
293050,36 months,A,A1,10+ years,MORTGAGE,Source Verified,Oct-14,Current,n,debt_consolidation,AL,Jan-96,f,Jan-16,Feb-16,Jan-16
213012,60 months,E,E5,5 years,MORTGAGE,Verified,Jun-12,Fully Paid,n,debt_consolidation,PA,Oct-00,f,Apr-13,NaN,Jul-15
371698,36 months,A,A4,10+ years,MORTGAGE,Not Verified,Jun-14,Fully Paid,n,debt_consolidation,PA,Feb-00,w,Jul-14,NaN,Sep-15
405069,60 months,D,D2,10+ years,MORTGAGE,Verified,Apr-14,Fully Paid,n,debt_consolidation,NY,Mar-89,w,Jan-16,NaN,Jan-16
343731,60 months,E,E2,10+ years,MORTGAGE,Not Verified,Jul-14,Fully Paid,n,debt_consolidation,WV,Mar-93,w,Dec-15,NaN,Dec-15
119988,36 months,A,A4,10+ years,MORTGAGE,Verified,Jul-13,Current,n,debt_consolidation,MA,Jul-96,f,Jan-16,Feb-16,Jan-16
100419,36 months,A,A1,3 years,MORTGAGE,Source Verified,Aug-13,Fully Paid,n,debt_consolidation,GA,Sep-81,f,Oct-15,NaN,Jan-16
117121,36 months,B,B1,6 years,MORTGAGE,Not Verified,Jul-13,Fully Paid,n,debt_consolidation,CA,Jul-98,f,Jan-14,NaN,Jan-14
139242,36 months,C,C5,10+ years,MORTGAGE,Verified,May-13,Current,n,credit_card,MA,Oct-88,f,Jan-16,Jan-16,Jan-16
344188,36 months,B,B1,8 years,MORTGAGE,Not Verified,Jul-14,Current,n,credit_card,AR,Jun-06,w,Jan-16,Feb-16,Jan-16

Terdapat satu fitur kategorikal yang dapat diubah menjadi biner secara numerik, yaitu `pymnt_plan`.

#### `pymnt_plan`

In [176]:
df['pymnt_plan_flag'] = df['pymnt_plan'].map({'y': 1, 'n': 0})

display(df[['pymnt_plan', 'pymnt_plan_flag']].sample(10))

       pymnt_plan  pymnt_plan_flag
192778          n                0
223598          n                0
260074          n                0
393283          n                0
431340          n                0
111032          n                0
361658          n                0
348702          n                0
247997          n                0
392818          n                0

Jangan lupa untuk mengubah fitur-fitur yang bisa jadi tipe data `date`, seperti `issue_d` dan `earliest_cr_line`.

In [177]:
df['earliest_cr_line_date'] = pd.to_datetime(df['earliest_cr_line'], format='%b-%y')
df['issue_d_date'] = pd.to_datetime(df['issue_d'], format='%b-%y')

display(df[['issue_d', 'issue_d_date', 'earliest_cr_line', 'earliest_cr_line_date']].sample(10))

       issue_d issue_d_date earliest_cr_line earliest_cr_line_date
441971  Feb-14   2014-02-01           Jul-91            1991-07-01
190528  Oct-12   2012-10-01           Nov-87            1987-11-01
416502  Apr-14   2014-04-01           Oct-03            2003-10-01
203753  Aug-12   2012-08-01           Sep-97            1997-09-01
400601  Apr-14   2014-04-01           Feb-77            1977-02-01
271120  Oct-14   2014-10-01           Sep-02            2002-09-01
392213  May-14   2014-05-01           Sep-87            1987-09-01
2564    Nov-11   2011-11-01           May-88            1988-05-01
459706  Jan-14   2014-01-01           Sep-03            2003-09-01
351799  Jul-14   2014-07-01           Dec-93            1993-12-01

Semua fitur yang telah diubah dapat dihapus untuk menghindari redundansi.

In [178]:
unused_features = ['pymnt_plan', 'issue_d', 'earliest_cr_line']
df = df.drop(columns=unused_features)

# rename the converted features to its original names
df = df.rename(columns={
    'pymnt_plan_flag': 'pymnt_plan',
})

display(
    df[['pymnt_plan']].sample(10)
)

        pymnt_plan
215493           0
246599           0
298579           0
167423           0
166310           0
57687            0
349445           0
188231           0
173640           0
240996           0

In [179]:
skim_result = utils.skim_data(df)

skim_result

Total duplicate rows: 0
DF shape: (466285, 45)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,loan_amnt,int64,0.000,0.0,0.0,1352,0.29,"[5000, 2500, 2400, 10000, 3000]"
1,funded_amnt,int64,0.000,0.0,0.0,1354,0.29,"[5000, 2500, 2400, 10000, 3000]"
2,funded_amnt_inv,float64,0.000,0.0,0.05,9854,2.11,"[4975.0, 2500.0, 2400.0, 10000.0, 3000.0]"
3,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
4,int_rate,float64,0.000,0.0,0.0,506,0.11,"[10.65, 15.27, 15.96, 13.49, 12.69]"
5,installment,float64,0.000,0.0,0.0,55622,11.93,"[162.87, 59.83, 84.33, 339.31, 67.79]"
6,grade,object,0.000,-,-,7,0.00,"[B, C, A, E, F]"
7,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, B5]"
8,emp_length,object,4.505,-,-,11,0.00,"[10+ years, < 1 year, 1 year, 3 years, 8 years]"
9,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
10,annual_inc,float64,0.001,0.0,0.0,31901,6.84,"[24000.0, 30000.0, 12252.0, 49200.0, 80000.0]"
11,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
12,loan_status,object,0.000,-,-,9,0.00,"[Fully Paid, Charged Off, Current, Default, La..."
13,purpose,object,0.000,-,-,14,0.00,"[credit_card, car, small_business, other, wedd..."
14,addr_state,object,0.000,-,-,50,0.01,"[AZ, GA, IL, CA, OR]"
15,dti,float64,0.000,0.0,0.078,3997,0.86,"[27.65, 1.0, 8.72, 20.0, 17.94]"
16,delinq_2yrs,float64,0.006,0.0,82.129,24,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
17,inq_last_6mths,float64,0.006,0.0,51.792,28,0.01,"[1.0, 5.0, 2.0, 0.0, 3.0]"
18,open_acc,float64,0.006,0.0,0.002,62,0.01,"[3.0, 2.0, 10.0, 15.0, 9.0]"
19,pub_rec,float64,0.006,0.0,86.834,26,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
20,revol_bal,int64,0.000,0.0,0.487,58142,12.47,"[13648, 1687, 2956, 5598, 27783]"
21,revol_util,float64,0.073,0.0,0.49,1269,0.27,"[83.7, 9.4, 98.5, 21.0, 53.9]"
22,total_acc,float64,0.006,0.0,0.0,112,0.02,"[9.0, 4.0, 10.0, 37.0, 38.0]"
23,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
24,out_prncp,float64,0.000,0.0,49.326,135665,29.09,"[0.0, 766.9, 1889.15, 2695.31, 3193.13]"
25,out_prncp_inv,float64,0.000,0.0,49.326,141189,30.28,"[0.0, 766.9, 1889.15, 2688.53, 3186.72]"
26,total_pymnt,float64,0.000,0.0,0.019,351609,75.41,"[5861.071414, 1008.71, 3003.653644, 12226.3022..."
27,total_pymnt_inv,float64,0.000,0.0,0.078,347659,74.56,"[5831.78, 1008.71, 3003.65, 12226.3, 3242.17]"
28,total_rec_prncp,float64,0.000,0.0,0.086,172713,37.04,"[5000.0, 456.46, 2400.0, 10000.0, 2233.1]"
29,total_rec_int,float64,0.000,0.0,0.081,270249,57.96,"[861.07, 435.17, 603.65, 2209.33, 1009.07]"
30,total_rec_late_fee,float64,0.000,0.0,97.71,5808,1.25,"[0.0, 16.97, 15.0, 24.17, 14.98883533]"
31,recoveries,float64,0.000,0.0,94.773,22773,4.88,"[0.0, 117.08, 189.06, 269.29, 444.3]"
32,collection_recovery_fee,float64,0.000,0.0,95.023,20275,4.35,"[0.0, 1.11, 2.09, 2.52, 4.16]"
33,last_pymnt_d,object,0.081,-,-,98,0.02,"[Jan-15, Apr-13, Jun-14, Jan-16, Apr-12]"
34,last_pymnt_amnt,float64,0.000,0.0,0.084,198194,42.50,"[171.62, 119.66, 649.91, 357.48, 67.79]"
35,next_pymnt_d,object,48.729,-,-,100,0.02,"[Feb-16, Jan-16, Sep-13, Feb-14, May-14]"
36,last_credit_pull_d,object,0.009,-,-,103,0.02,"[Jan-16, Sep-13, Jan-15, Sep-15, Dec-14]"
37,collections_12_mths_ex_med,float64,0.031,0.0,99.13,9,0.00,"[0.0, 1.0, 2.0, 4.0, 3.0]"
38,acc_now_delinq,float64,0.006,0.0,99.622,6,0.00,"[0.0, 1.0, 2.0, 3.0, 5.0]"
39,tot_coll_amt,float64,15.071,0.0,74.259,6321,1.36,"[0.0, 15386.0, 1514.0, 154.0, 539.0]"
40,tot_cur_bal,float64,15.071,0.0,0.017,220690,47.33,"[114834.0, 14123.0, 267646.0, 13605.0, 272492.0]"
41,total_rev_hi_lim,float64,15.071,0.0,0.033,14612,3.13,"[59900.0, 15100.0, 61100.0, 8100.0, 15400.0]"
42,pymnt_plan,int64,0.000,0.0,99.998,2,0.00,"[0, 1]"
43,earliest_cr_line_date,datetime64[ns],0.006,-,-,664,0.14,"[1985-01-01 00:00:00, 1999-04-01 00:00:00, 200..."
44,issue_d_date,datetime64[ns],0.000,-,-,91,0.02,"[2011-12-01 00:00:00, 2011-11-01 00:00:00, 201..."

### High Probability of Data Leakage

Dalam konteks credit risk assessment, fitur-fitur ini dianggap sebagai `data leakage` karena fitur tersebut mengandung informasi masa depan yang tidak tersedia saat pengambilan keputusan kredit ketika aplikasi itu diajukan. Fitur-fitur tersebut adalah:

- `out_prncp`
- `out_prncp_inv`
- `total_pymnt`
- `total_pymnt_inv`
- `total_rec_prncp`
- `total_rec_int`
- `total_rec_late_fee`
- `recoveries`
- `collection_recovery_fee`
- `last_pymnt_d`
- `last_pymnt_amnt`
- `next_pymnt_d`
- `last_credit_pull_d`

In [180]:
potential_leak_features = ['out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
                           'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
                           'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
                           'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d']
df = df.drop(columns=potential_leak_features)
skim_result = utils.skim_data(df)

skim_result

Total duplicate rows: 0
DF shape: (466285, 32)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,loan_amnt,int64,0.000,0.0,0.0,1352,0.29,"[5000, 2500, 2400, 10000, 3000]"
1,funded_amnt,int64,0.000,0.0,0.0,1354,0.29,"[5000, 2500, 2400, 10000, 3000]"
2,funded_amnt_inv,float64,0.000,0.0,0.05,9854,2.11,"[4975.0, 2500.0, 2400.0, 10000.0, 3000.0]"
3,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
4,int_rate,float64,0.000,0.0,0.0,506,0.11,"[10.65, 15.27, 15.96, 13.49, 12.69]"
5,installment,float64,0.000,0.0,0.0,55622,11.93,"[162.87, 59.83, 84.33, 339.31, 67.79]"
6,grade,object,0.000,-,-,7,0.00,"[B, C, A, E, F]"
7,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, B5]"
8,emp_length,object,4.505,-,-,11,0.00,"[10+ years, < 1 year, 1 year, 3 years, 8 years]"
9,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
10,annual_inc,float64,0.001,0.0,0.0,31901,6.84,"[24000.0, 30000.0, 12252.0, 49200.0, 80000.0]"
11,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
12,loan_status,object,0.000,-,-,9,0.00,"[Fully Paid, Charged Off, Current, Default, La..."
13,purpose,object,0.000,-,-,14,0.00,"[credit_card, car, small_business, other, wedd..."
14,addr_state,object,0.000,-,-,50,0.01,"[AZ, GA, IL, CA, OR]"
15,dti,float64,0.000,0.0,0.078,3997,0.86,"[27.65, 1.0, 8.72, 20.0, 17.94]"
16,delinq_2yrs,float64,0.006,0.0,82.129,24,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
17,inq_last_6mths,float64,0.006,0.0,51.792,28,0.01,"[1.0, 5.0, 2.0, 0.0, 3.0]"
18,open_acc,float64,0.006,0.0,0.002,62,0.01,"[3.0, 2.0, 10.0, 15.0, 9.0]"
19,pub_rec,float64,0.006,0.0,86.834,26,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
20,revol_bal,int64,0.000,0.0,0.487,58142,12.47,"[13648, 1687, 2956, 5598, 27783]"
21,revol_util,float64,0.073,0.0,0.49,1269,0.27,"[83.7, 9.4, 98.5, 21.0, 53.9]"
22,total_acc,float64,0.006,0.0,0.0,112,0.02,"[9.0, 4.0, 10.0, 37.0, 38.0]"
23,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
24,collections_12_mths_ex_med,float64,0.031,0.0,99.13,9,0.00,"[0.0, 1.0, 2.0, 4.0, 3.0]"
25,acc_now_delinq,float64,0.006,0.0,99.622,6,0.00,"[0.0, 1.0, 2.0, 3.0, 5.0]"
26,tot_coll_amt,float64,15.071,0.0,74.259,6321,1.36,"[0.0, 15386.0, 1514.0, 154.0, 539.0]"
27,tot_cur_bal,float64,15.071,0.0,0.017,220690,47.33,"[114834.0, 14123.0, 267646.0, 13605.0, 272492.0]"
28,total_rev_hi_lim,float64,15.071,0.0,0.033,14612,3.13,"[59900.0, 15100.0, 61100.0, 8100.0, 15400.0]"
29,pymnt_plan,int64,0.000,0.0,99.998,2,0.00,"[0, 1]"
30,earliest_cr_line_date,datetime64[ns],0.006,-,-,664,0.14,"[1985-01-01 00:00:00, 1999-04-01 00:00:00, 200..."
31,issue_d_date,datetime64[ns],0.000,-,-,91,0.02,"[2011-12-01 00:00:00, 2011-11-01 00:00:00, 201..."

### Low-variance Features

Dari semua fitur yang telah disaring dan dibuat baru, mari cek `skim_result` terkini. Ada tiga fitur yang memiliki nilai 0 lebih dari 99% data, yaitu `collections_12_mths_ex_med`, `acc_now_delinq`, dan `pymnt_plan`. Ini menunjukkan kalau ketiga fitur tersebut bersifat *low-variance* sehingga tidak bermanfaat dalam pembuatan model.

In [181]:
low_var_features = ['collections_12_mths_ex_med', 'acc_now_delinq', 'pymnt_plan']
df = df.drop(columns=low_var_features)
skim_result = utils.skim_data(df)

skim_result

Total duplicate rows: 0
DF shape: (466285, 29)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,loan_amnt,int64,0.000,0.0,0.0,1352,0.29,"[5000, 2500, 2400, 10000, 3000]"
1,funded_amnt,int64,0.000,0.0,0.0,1354,0.29,"[5000, 2500, 2400, 10000, 3000]"
2,funded_amnt_inv,float64,0.000,0.0,0.05,9854,2.11,"[4975.0, 2500.0, 2400.0, 10000.0, 3000.0]"
3,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
4,int_rate,float64,0.000,0.0,0.0,506,0.11,"[10.65, 15.27, 15.96, 13.49, 12.69]"
5,installment,float64,0.000,0.0,0.0,55622,11.93,"[162.87, 59.83, 84.33, 339.31, 67.79]"
6,grade,object,0.000,-,-,7,0.00,"[B, C, A, E, F]"
7,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, B5]"
8,emp_length,object,4.505,-,-,11,0.00,"[10+ years, < 1 year, 1 year, 3 years, 8 years]"
9,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
10,annual_inc,float64,0.001,0.0,0.0,31901,6.84,"[24000.0, 30000.0, 12252.0, 49200.0, 80000.0]"
11,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
12,loan_status,object,0.000,-,-,9,0.00,"[Fully Paid, Charged Off, Current, Default, La..."
13,purpose,object,0.000,-,-,14,0.00,"[credit_card, car, small_business, other, wedd..."
14,addr_state,object,0.000,-,-,50,0.01,"[AZ, GA, IL, CA, OR]"
15,dti,float64,0.000,0.0,0.078,3997,0.86,"[27.65, 1.0, 8.72, 20.0, 17.94]"
16,delinq_2yrs,float64,0.006,0.0,82.129,24,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
17,inq_last_6mths,float64,0.006,0.0,51.792,28,0.01,"[1.0, 5.0, 2.0, 0.0, 3.0]"
18,open_acc,float64,0.006,0.0,0.002,62,0.01,"[3.0, 2.0, 10.0, 15.0, 9.0]"
19,pub_rec,float64,0.006,0.0,86.834,26,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
20,revol_bal,int64,0.000,0.0,0.487,58142,12.47,"[13648, 1687, 2956, 5598, 27783]"
21,revol_util,float64,0.073,0.0,0.49,1269,0.27,"[83.7, 9.4, 98.5, 21.0, 53.9]"
22,total_acc,float64,0.006,0.0,0.0,112,0.02,"[9.0, 4.0, 10.0, 37.0, 38.0]"
23,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
24,tot_coll_amt,float64,15.071,0.0,74.259,6321,1.36,"[0.0, 15386.0, 1514.0, 154.0, 539.0]"
25,tot_cur_bal,float64,15.071,0.0,0.017,220690,47.33,"[114834.0, 14123.0, 267646.0, 13605.0, 272492.0]"
26,total_rev_hi_lim,float64,15.071,0.0,0.033,14612,3.13,"[59900.0, 15100.0, 61100.0, 8100.0, 15400.0]"
27,earliest_cr_line_date,datetime64[ns],0.006,-,-,664,0.14,"[1985-01-01 00:00:00, 1999-04-01 00:00:00, 200..."
28,issue_d_date,datetime64[ns],0.000,-,-,91,0.02,"[2011-12-01 00:00:00, 2011-11-01 00:00:00, 201..."

### Redundant Features

Selanjutnya, terdapat masalah redundansi antara `grade` dan `sub_grade` dalam arti informasinya; `sub_grade` sudah mencakup `grade` dengan informasi level yang lebih detil. Saya akan memilih `sub_grade` karena level detil informasinya lebih tinggi dibanding `grade`, dengan harapan dapat meningkatkan performa dari model.

In [182]:
print(f'Grade values: {df['grade'].unique()}')
print(f'\nSubgrade values: {df['sub_grade'].unique()}')

Grade values: ['B' 'C' 'A' 'E' 'F' 'D' 'G']

Subgrade values: ['B2' 'C4' 'C5' 'C1' 'B5' 'A4' 'E1' 'F2' 'C3' 'B1' 'D1' 'A1' 'B3' 'B4'
 'C2' 'D2' 'A3' 'A5' 'D5' 'A2' 'E4' 'D3' 'D4' 'F3' 'E3' 'F4' 'F1' 'E5'
 'G4' 'E2' 'G3' 'G2' 'G1' 'F5' 'G5']

In [183]:
df = df.drop(columns=['grade'])
skim_result = utils.skim_data(df)

skim_result

Total duplicate rows: 0
DF shape: (466285, 28)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,loan_amnt,int64,0.000,0.0,0.0,1352,0.29,"[5000, 2500, 2400, 10000, 3000]"
1,funded_amnt,int64,0.000,0.0,0.0,1354,0.29,"[5000, 2500, 2400, 10000, 3000]"
2,funded_amnt_inv,float64,0.000,0.0,0.05,9854,2.11,"[4975.0, 2500.0, 2400.0, 10000.0, 3000.0]"
3,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
4,int_rate,float64,0.000,0.0,0.0,506,0.11,"[10.65, 15.27, 15.96, 13.49, 12.69]"
5,installment,float64,0.000,0.0,0.0,55622,11.93,"[162.87, 59.83, 84.33, 339.31, 67.79]"
6,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, B5]"
7,emp_length,object,4.505,-,-,11,0.00,"[10+ years, < 1 year, 1 year, 3 years, 8 years]"
8,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
9,annual_inc,float64,0.001,0.0,0.0,31901,6.84,"[24000.0, 30000.0, 12252.0, 49200.0, 80000.0]"
10,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
11,loan_status,object,0.000,-,-,9,0.00,"[Fully Paid, Charged Off, Current, Default, La..."
12,purpose,object,0.000,-,-,14,0.00,"[credit_card, car, small_business, other, wedd..."
13,addr_state,object,0.000,-,-,50,0.01,"[AZ, GA, IL, CA, OR]"
14,dti,float64,0.000,0.0,0.078,3997,0.86,"[27.65, 1.0, 8.72, 20.0, 17.94]"
15,delinq_2yrs,float64,0.006,0.0,82.129,24,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
16,inq_last_6mths,float64,0.006,0.0,51.792,28,0.01,"[1.0, 5.0, 2.0, 0.0, 3.0]"
17,open_acc,float64,0.006,0.0,0.002,62,0.01,"[3.0, 2.0, 10.0, 15.0, 9.0]"
18,pub_rec,float64,0.006,0.0,86.834,26,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
19,revol_bal,int64,0.000,0.0,0.487,58142,12.47,"[13648, 1687, 2956, 5598, 27783]"
20,revol_util,float64,0.073,0.0,0.49,1269,0.27,"[83.7, 9.4, 98.5, 21.0, 53.9]"
21,total_acc,float64,0.006,0.0,0.0,112,0.02,"[9.0, 4.0, 10.0, 37.0, 38.0]"
22,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
23,tot_coll_amt,float64,15.071,0.0,74.259,6321,1.36,"[0.0, 15386.0, 1514.0, 154.0, 539.0]"
24,tot_cur_bal,float64,15.071,0.0,0.017,220690,47.33,"[114834.0, 14123.0, 267646.0, 13605.0, 272492.0]"
25,total_rev_hi_lim,float64,15.071,0.0,0.033,14612,3.13,"[59900.0, 15100.0, 61100.0, 8100.0, 15400.0]"
26,earliest_cr_line_date,datetime64[ns],0.006,-,-,664,0.14,"[1985-01-01 00:00:00, 1999-04-01 00:00:00, 200..."
27,issue_d_date,datetime64[ns],0.000,-,-,91,0.02,"[2011-12-01 00:00:00, 2011-11-01 00:00:00, 201..."

### Defining "Good Loan" vs. "Bad Loan"

Tujuan utama model yang akan dibuat adalah untuk menjawal pertanyaan bisnis sederhana: "apakah nasabah ini akan Gagal Bayar di masa depan", yang membuat permasalahan ini menjadi masalah klasifikasi biner.

Dalam `loan_status` sekarang, ada sembilan nilai unik yang harus dipilah agar dapat menjadi 1 (Gagal Bayar) atau 0 (Sukses Bayar):

In [184]:
df['loan_status'].unique()

array(['Fully Paid', 'Charged Off', 'Current', 'Default',
       'Late (31-120 days)', 'In Grace Period', 'Late (16-30 days)',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

Untuk memilih kelompok Gagal Bayar, saya akan memilih semua variasi `Charged Off`, `Default`, dan variasi `Late (x days)`, karena saya ingin model ini secara proaktif mengidentifikasi calon nasabah yang berpotensi menyebabkan kerugian finansial bagi perusahaan.

Untuk memilih kelompok Sukses Bayar, saya akan memilih semua variasi `Fully Paid`, karena ini adalah mayoritas nasabah yang baik dan menguntungkan. Model harus bisa membedakan mereka dari kelompok berisiko.

Baris data yang tidak tergolong dalam dua kelompok di atas akan dibuang.

In [185]:
print(f'DataFrame sizes before selection: {df.shape}\n')
good_loan_statuses = [
    'Fully Paid', 
    'Does not meet the credit policy. Status:Fully Paid'
]
bad_loan_statuses = [
    'Charged Off', 
    'Default', 
    'Late (31-120 days)', 
    'Late (16-30 days)',
    'Does not meet the credit policy. Status:Charged Off'
]
df = df[df['loan_status'].isin(good_loan_statuses + bad_loan_statuses)].copy()
df['loan_status_binary'] = df['loan_status'].apply(
    lambda x: 1 if x in bad_loan_statuses else 0
)
# remove loan_status and replace with loan_status_binary
df = df.drop(columns=['loan_status'])
df = df.rename(columns={'loan_status_binary': 'loan_status'})
skim_result = utils.skim_data(df)

skim_result

DataFrame sizes before selection: (466285, 28)

Total duplicate rows: 0
DF shape: (238913, 28)

,feature,dtype,null_%,negative_%,zero_%,n_unique,unique_%,sample_values
0,loan_amnt,int64,0.000,0.0,0.0,1310,0.55,"[5000, 2500, 2400, 10000, 3000]"
1,funded_amnt,int64,0.000,0.0,0.0,1313,0.55,"[5000, 2500, 2400, 10000, 3000]"
2,funded_amnt_inv,float64,0.000,0.0,0.098,9560,4.00,"[4975.0, 2500.0, 2400.0, 10000.0, 5000.0]"
3,term,object,0.000,-,-,2,0.00,"[ 36 months, 60 months]"
4,int_rate,float64,0.000,0.0,0.0,505,0.21,"[10.65, 15.27, 15.96, 13.49, 7.9]"
5,installment,float64,0.000,0.0,0.0,43848,18.35,"[162.87, 59.83, 84.33, 339.31, 156.46]"
6,sub_grade,object,0.000,-,-,35,0.01,"[B2, C4, C5, C1, A4]"
7,emp_length,object,3.861,-,-,11,0.00,"[10+ years, < 1 year, 3 years, 9 years, 4 years]"
8,home_ownership,object,0.000,-,-,6,0.00,"[RENT, OWN, MORTGAGE, OTHER, NONE]"
9,annual_inc,float64,0.002,0.0,0.0,18715,7.83,"[24000.0, 30000.0, 12252.0, 49200.0, 36000.0]"
10,verification_status,object,0.000,-,-,3,0.00,"[Verified, Source Verified, Not Verified]"
11,purpose,object,0.000,-,-,14,0.01,"[credit_card, car, small_business, other, wedd..."
12,addr_state,object,0.000,-,-,50,0.02,"[AZ, GA, IL, CA, TX]"
13,dti,float64,0.000,0.0,0.126,3912,1.64,"[27.65, 1.0, 8.72, 20.0, 11.2]"
14,delinq_2yrs,float64,0.012,0.0,83.954,23,0.01,"[0.0, 2.0, 3.0, 1.0, 4.0]"
15,inq_last_6mths,float64,0.012,0.0,47.857,28,0.01,"[1.0, 5.0, 2.0, 3.0, 0.0]"
16,open_acc,float64,0.012,0.0,0.003,57,0.02,"[3.0, 2.0, 10.0, 9.0, 4.0]"
17,pub_rec,float64,0.012,0.0,88.405,12,0.01,"[0.0, 1.0, 2.0, 3.0, 4.0]"
18,revol_bal,int64,0.000,0.0,0.742,46451,19.44,"[13648, 1687, 2956, 5598, 7963]"
19,revol_util,float64,0.097,0.0,0.734,1203,0.50,"[83.7, 9.4, 98.5, 21.0, 28.3]"
20,total_acc,float64,0.012,0.0,0.0,102,0.04,"[9.0, 4.0, 10.0, 37.0, 12.0]"
21,initial_list_status,object,0.000,-,-,2,0.00,"[f, w]"
22,tot_coll_amt,float64,27.886,0.0,63.997,3713,1.55,"[15386.0, 154.0, 0.0, 539.0, 92.0]"
23,tot_cur_bal,float64,27.886,0.0,0.019,125106,52.36,"[13605.0, 19530.0, 799592.0, 199834.0, 15949.0]"
24,total_rev_hi_lim,float64,27.886,0.0,0.034,9194,3.85,"[8100.0, 5300.0, 54200.0, 28200.0, 20800.0]"
25,earliest_cr_line_date,datetime64[ns],0.012,-,-,634,0.27,"[1985-01-01 00:00:00, 1999-04-01 00:00:00, 200..."
26,issue_d_date,datetime64[ns],0.000,-,-,91,0.04,"[2011-12-01 00:00:00, 2011-11-01 00:00:00, 201..."
27,loan_status,int64,0.000,0.0,78.157,2,0.00,"[0, 1]"

Terlihat ada pengurangan sebanyak 226.721 baris data dari `loan_status` berlabel `Current` dan `In Grace Period`. Sekilas ini terlihat seperti pemborosan data, tapi saya berpegang teguh bahwa kualitas data lebih penting daripada kuantitas data. Data tersebut adalah noise, dan mempertahankan noise akan berakibat fatal yang dapat merusak kemampuan model untuk belajar.

## Splitting Data

In [186]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['loan_status'])
y = df[['loan_status']]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=29, stratify=y
)

In [187]:
print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (191130, 27)
X_test shape: (47783, 27)

In [188]:
df_train = pd.concat([X_train, y_train], axis=1)
df_train.to_parquet('input/df_train.parquet', index=False)
df_test = pd.concat([X_test, y_test], axis=1)
df_test.to_parquet('input/df_test.parquet', index=False)